name: Container-4
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
      # 這裡將 repo checkout 後，檔案會帶往下面的 steps
      - uses: actions/checkout@v1
      - name: display file list
        run: ls -a
      # 執行 repo 中的 script.sh 檔案
      - name: run a script
        uses: docker://alpine
        with:
          entrypoint: ./script.sh
          args: 'hello-world'