name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: ndoe:13.5.0-alpine3.10
    steps:
      - name: display node version
        run: |
          node -v
          cat /etc/os-release