name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:10.23.0-alpine3.11
    steps:
      - name: display node version
        run: |
          node -v
          cat /etc/os-release