name: Container-3
on: pull_request

jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    # container: node:10.18-jessie

    services:
      redis:
        image: redis
        # 在 step 中的 container 會與 service container 使用相同的 docker network
        # 因此就不需要開啟 port mapping 了
        # ports:
        #   - 6379:6379

    steps:
      - name: test redis connection
        uses: docker://redis
        with:
          entrypoint: '/usr/local/bin/redis-cli'
          args: '-h redis ping'