name: Container-3
on: push

jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    # container: node:10.18-jessie

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: test redis connection
        uses: docker://redis
        with:
          entrypoint: ['/usr/local/bin/redis-cli']
          args: ['-h', 'redis', 'ping']