name: Container-4
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: display file list
        run: ls -a
      - name: run a script
        uses: docker://node
        with:
          entrypoint: ./script.sh
          args: 'hello-world'