name: matrix test

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
      include:
        - os: ubuntu-latest
          node_version: 10
          is_ubuntu_10: 'true'
      exclude:
        - os: macos-latest
          node_version: 6
        - os: ubuntu-latest
          node_version: 8
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_10: ${{ matrix.is_ubuntu_10 }}
    steps:
      - name: display node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: display node version after setup-node
        run: |
          node -v
          echo "IS_UBUNTU_10 = $IS_UBUNTU_10"