name: matrix test

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: display node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: display node version after setup-node
        run: node -v