name: matrix test

on: push

jobs:
  node-version:
    strategy:
      matrix:
        node_version: [6, 8, 10]
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: display node version
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: display node version after setup-node
        run: node -v